import type { Metadata } from "next";
import localFont from "next/font/local";
import { AppProvider } from "@/context/AppContext";
import WebGLStage from "@/components/webgl/WebGLStage";
import "./globals.css";

const bamq = localFont({
  src: [
    {
      path: "../assets/fonts/Bamq/Bamq-Regular.woff2",
      weight: "normal",
      style: "normal",
    },
    {
      path: "../assets/fonts/Bamq/Bamq-Bold.woff2",
      weight: "bold",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-bamq",
});

export const metadata: Metadata = {
  title: "Alexandra Smith | Full-Stack Web Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="bg-gradient-to-t from-nse-pink-900 from-[1%] via-[#001949] to-nse-black bg-fixed"
    >
    <body className={`${bamq.variable} font-syne antialiased`}>
    <AppProvider>
      <WebGLStage>{children}</WebGLStage>
    </AppProvider>
    </body>
    </html>
  );
}
